
baseURL = 'https://yoyolooming.github.io/'
languageCode = 'zh-cn'
title = 'yoyo_looming's blog'
theme = "diary"
DefaultContentLanguage = "zh-cn" # Theme's display language, supports: en, fr, zh, zh-hant
copyright = "This is a customized copyright."


[params]
subtitle = "我很想念你."
enableGiscus = true
enableTOC = true
showWordCount = true
showReadingTime = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data_repo="username/repo"
    data_repo_id="**************************"    
    data_category="General"
    data_category_id="*********************"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="en"
    crossorigin="anonymous"


[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4
[[menu.main]]
url = "/about"
name = "关于"
weight = 5